from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_lesson_video_lesson_questions_completion"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "courses_lessonquestion" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "text" text NOT NULL,
                "explanation" text NOT NULL,
                "at_seconds" integer NULL,
                "points" integer NOT NULL CHECK ("points" >= 0),
                "order" integer NOT NULL CHECK ("order" >= 0),
                "lesson_id" bigint NOT NULL REFERENCES "courses_lesson" ("id") ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS "courses_lessonquestionchoice" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "text" varchar(400) NOT NULL,
                "is_correct" boolean NOT NULL,
                "order" integer NOT NULL CHECK ("order" >= 0),
                "question_id" bigint NOT NULL REFERENCES "courses_lessonquestion" ("id") ON DELETE CASCADE
            );
            CREATE TABLE IF NOT EXISTS "courses_lessonquestionattempt" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "is_correct" boolean NOT NULL,
                "points_awarded" integer NOT NULL CHECK ("points_awarded" >= 0),
                "attempted_at" timestamptz NOT NULL,
                "question_id" bigint NOT NULL REFERENCES "courses_lessonquestion" ("id") ON DELETE CASCADE,
                "selected_choice_id" bigint REFERENCES "courses_lessonquestionchoice" ("id") ON DELETE SET NULL,
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE,
                UNIQUE ("user_id", "question_id")
            );
            CREATE TABLE IF NOT EXISTS "courses_userlessonprogress" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "is_completed" boolean NOT NULL,
                "completed_at" timestamptz NULL,
                "lesson_id" bigint NOT NULL REFERENCES "courses_lesson" ("id") ON DELETE CASCADE,
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE,
                UNIQUE ("user_id", "lesson_id")
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
